import React, { useState, useEffect } from "react";
import { Mail, X, Trash2, Check, Inbox, ExternalLink, RefreshCw } from "lucide-react";
import { api } from "../lib/api.js";
import { EmailLog } from "../types.js";

export default function EmailSimulator() {
  const [emails, setEmails] = useState<EmailLog[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [selectedEmail, setSelectedEmail] = useState<EmailLog | null>(null);
  const [unreadCount, setUnreadCount] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [showClearConfirm, setShowClearConfirm] = useState(false);

  const fetchEmails = async () => {
    try {
      setIsLoading(true);
      const data = await api.admin.emails.list();
      if (Array.isArray(data)) {
        setEmails(data);
        // Track previous length and trigger highlight if increased
        if (data.length > emails.length && emails.length > 0) {
          setUnreadCount((prev) => prev + (data.length - emails.length));
        }
      }
    } catch (e: any) {
      console.warn("Could not load simulation email logs:", e?.message || e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchEmails();
    // Poll for new emails every 4 seconds to simulate real-time notification arrivals
    const interval = setInterval(fetchEmails, 4000);
    return () => clearInterval(interval);
  }, [emails.length]);

  const handleClearAll = () => {
    setShowClearConfirm(true);
  };

  const handleConfirmClearAll = async () => {
    try {
      await api.admin.emails.clear();
      setEmails([]);
      setSelectedEmail(null);
      setUnreadCount(0);
      setShowClearConfirm(false);
    } catch (e) {
      console.error("Failed to clear email logs:", e);
    }
  };

  const handleOpenEmail = (email: EmailLog) => {
    setSelectedEmail(email);
  };

  const handleClose = () => {
    setIsOpen(false);
    setUnreadCount(0);
  };

  return (
    <>
      {/* Floating Action Button */}
      <button
        id="btn-trigger-email-simulator"
        onClick={() => {
          setIsOpen(true);
          setUnreadCount(0);
        }}
        className="fixed bottom-6 right-6 z-50 flex items-center gap-2 bg-blue-600 hover:bg-blue-700 active:scale-95 text-white px-4 py-2.5 rounded-full shadow-lg transition-all cursor-pointer font-bold text-xs group border border-blue-500 animate-bounce"
        title="Open Simulated Email Logs"
      >
        <div className="relative">
          <Mail className="h-4.5 w-4.5 group-hover:rotate-6 transition-transform" />
          {unreadCount > 0 && (
            <span className="absolute -top-2 -right-2 bg-rose-500 border-2 border-blue-600 text-[9px] font-bold h-4 w-4 flex items-center justify-center rounded-full">
              {unreadCount}
            </span>
          )}
          {emails.length > 0 && unreadCount === 0 && (
            <span className="absolute top-0 right-0 h-2 w-2 bg-emerald-400 rounded-full border border-blue-600 animate-pulse" />
          )}
        </div>
        <span className="max-w-px overflow-hidden group-hover:max-w-xs transition-all duration-300 ease-out whitespace-nowrap text-[10px] uppercase tracking-wider font-extrabold ml-1">
          EduMail Simulator ({emails.length})
        </span>
      </button>

      {/* Simulator Modal Drawers */}
      {isOpen && (
        <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-lg w-full max-w-5xl h-[80vh] shadow-xl border border-slate-200 flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            
            {/* Header */}
            <div className="bg-slate-900 text-white px-5 py-3.5 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="bg-slate-800 p-1.5 rounded">
                  <Mail className="h-4.5 w-4.5 text-blue-400" />
                </div>
                <div className="text-left">
                  <h3 className="font-extrabold text-xs uppercase tracking-wider flex items-center gap-2">
                    EduMail System Simulator
                    <span className="bg-blue-900/80 text-[9px] px-2 py-0.5 rounded font-mono text-blue-200 font-bold border border-blue-700 uppercase tracking-widest">
                      Sandbox Output
                    </span>
                  </h3>
                  <p className="text-[10px] text-slate-400 mt-0.5">
                    Observe real-time interactive HTML emails generated by automatic supervision logs in the Express background
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={fetchEmails}
                  disabled={isLoading}
                  className="p-1.5 hover:bg-slate-800 rounded text-slate-300 hover:text-white transition-colors cursor-pointer"
                  title="Force Refresh Inbox"
                >
                  <RefreshCw className={`h-3.5 w-3.5 ${isLoading ? "animate-spin" : ""}`} />
                </button>
                {emails.length > 0 && (
                  <button
                    onClick={handleClearAll}
                    className="p-1.5 hover:bg-rose-500/20 hover:text-rose-200 rounded text-slate-350 transition-all cursor-pointer flex items-center gap-1 text-xs font-bold uppercase tracking-wider"
                    title="Clear Log History"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                    <span className="text-[10px]">Clear List</span>
                  </button>
                )}
                <button
                  onClick={handleClose}
                  className="p-1.5 hover:bg-slate-800 rounded text-slate-355 hover:text-white transition-colors cursor-pointer"
                >
                  <X className="h-4.5 w-4.5" />
                </button>
              </div>
            </div>

            {/* Email Layout Panels */}
            <div className="flex-1 flex overflow-hidden bg-slate-50">
              
              {/* Left Column: Email List */}
              <div className="w-1/3 border-r border-slate-200 flex flex-col bg-white">
                <div className="p-3 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
                  <span className="text-[10px] font-extrabold text-slate-500 tracking-wider uppercase">
                    Inbox Folders ({emails.length})
                  </span>
                  <span className="text-[9px] text-slate-400 font-bold uppercase tracking-widest font-mono">Auto poll</span>
                </div>

                <div className="flex-1 overflow-y-auto divide-y divide-slate-100">
                  {emails.length === 0 ? (
                    <div className="p-6 text-center text-slate-405 mt-10">
                      <Inbox className="h-8 w-8 mx-auto text-slate-305 stroke-[1.5] mb-2" />
                      <p className="text-xs font-semibold">Your Simulator Inbox is empty</p>
                      <p className="text-[10px] text-slate-400 max-w-[180px] mx-auto mt-1 leading-relaxed">
                        Trigger automated notifications by registering, altering statuses, or scheduling supervisions.
                      </p>
                    </div>
                  ) : (
                    emails.map((email) => {
                      const isSelected = selectedEmail?.id === email.id;
                      return (
                        <div
                          key={email.id}
                          onClick={() => handleOpenEmail(email)}
                          className={`p-3 cursor-pointer text-left transition-all ${
                            isSelected
                              ? "bg-slate-50 border-l-3 border-blue-600 font-medium"
                              : "hover:bg-slate-50/50 border-l-3 border-transparent"
                          }`}
                        >
                          <div className="flex justify-between items-start gap-1 mb-1">
                            <span className="text-[9px] font-bold text-slate-655 bg-slate-100 px-1.5 py-0.5 rounded truncate max-w-[110px]">
                              To: {email.to.split("@")[0]}
                            </span>
                            <span className="text-[9px] text-slate-400 bg-white px-1 py-0.5 border border-slate-200 rounded font-mono">
                              {new Date(email.sentAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
                            </span>
                          </div>
                          <h4 className="text-xs font-bold text-slate-900 truncate">
                            {email.subject}
                          </h4>
                          <p className="text-[10px] text-slate-450 line-clamp-2 mt-0.5 leading-relaxed font-sans">
                            {email.html.replace(/<[^>]*>/g, "").trim()}
                          </p>
                        </div>
                      );
                    })
                  )}
                </div>
              </div>

              {/* Right Column: Display Area */}
              <div className="flex-1 flex flex-col bg-slate-50 overflow-hidden">
                {selectedEmail ? (
                  <div className="flex-1 flex flex-col overflow-hidden bg-white m-3 rounded border border-slate-200 shadow-xs">
                    
                    {/* Header */}
                    <div className="p-3.5 border-b border-slate-205 bg-slate-50/70">
                      <div className="flex items-start justify-between gap-4 text-left">
                        <div className="space-y-0.5">
                          <h2 className="text-xs font-extrabold text-slate-950">
                            {selectedEmail.subject}
                          </h2>
                          <div className="flex flex-wrap gap-x-3 gap-y-0.5 text-[10px] text-slate-600 pt-0.5 font-medium">
                            <div>
                              <span className="text-slate-400">From:</span>{" "}
                              <span className="text-slate-900 font-bold">Registry System Bot &lt;noreply@university.edu&gt;</span>
                            </div>
                            <div>
                              <span className="text-slate-400">To:</span>{" "}
                              <span className="text-blue-700 font-bold bg-blue-50 px-1 py-0.2 rounded font-mono">{selectedEmail.to}</span>
                            </div>
                          </div>
                        </div>
                        <div className="text-right whitespace-nowrap text-[10px] text-slate-400 font-mono">
                          {new Date(selectedEmail.sentAt).toLocaleDateString()} {new Date(selectedEmail.sentAt).toLocaleTimeString()}
                        </div>
                      </div>
                    </div>

                    {/* HTML Iframe Preview Layer */}
                    <div className="flex-1 overflow-y-auto p-4 bg-slate-50">
                      <div className="bg-white rounded shadow-xs border border-slate-200 p-2.5 max-w-[620px] mx-auto">
                        <div
                          className="p-3 rounded"
                          dangerouslySetInnerHTML={{ __html: selectedEmail.html }}
                        />
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex-1 flex flex-col items-center justify-center p-8 text-slate-400">
                    <Mail className="h-10 w-10 text-slate-250 mb-2 stroke-[1]" />
                    <h4 className="font-semibold text-xs text-slate-750">No Email Selected</h4>
                    <p className="text-[11px] text-slate-405 mt-0.5 max-w-xs text-center">
                      Select an incoming automatic trigger notification message from the left folder sidebar to view its fully compiled responsive HTML template payload.
                    </p>
                  </div>
                )}
              </div>

            </div>

            {/* Bottom Info Bar Footer */}
            <div className="bg-slate-100 px-4 py-1.5 border-t border-slate-200 text-center text-[9px] text-slate-500 flex items-center justify-between font-medium">
              <span>SMTP Host: <code className="bg-slate-200 px-1 rounded font-bold">localhost (Sandboxed Inside Container)</code></span>
              <span>Communication sandbox active. Actions in current sessions trigger automated mailers immediately.</span>
              <span className="flex items-center gap-0.5 text-blue-750 font-bold">
                <Check className="h-3.5 w-3.5 text-emerald-500" /> Live Communication Tunnel Established
              </span>
            </div>

          </div>
        </div>
      )}

      {/* Clear Confirmation Overlay */}
      {showClearConfirm && (
        <div className="fixed inset-0 z-[200] bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-lg border border-slate-200 shadow-2xl w-full max-w-sm p-5 text-left animate-in zoom-in-95 duration-150">
            <div className="flex items-center gap-3 text-rose-600 mb-3.5">
              <div className="p-2.5 bg-rose-50 rounded-full">
                <Trash2 className="h-6 w-6 stroke-[2]" />
              </div>
              <div>
                <h3 className="font-extrabold text-sm text-slate-900 font-sans">Clear Simulated Inbox?</h3>
                <p className="text-[10px] text-slate-400 font-semibold font-mono uppercase tracking-wider">Communication Logs Clearance</p>
              </div>
            </div>

            <p className="text-slate-705 text-xs mb-4 leading-relaxed font-semibold">
              Are you sure you want to clear the simulated email log history? This will permanently wipe the active list records.
            </p>

            <div className="flex justify-end gap-2 pr-1">
              <button
                type="button"
                onClick={() => setShowClearConfirm(false)}
                className="px-3.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs rounded transition-all cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirmClearAll}
                className="px-4 py-1.5 bg-rose-600 hover:bg-rose-700 text-white font-bold text-xs rounded transition-all cursor-pointer shadow-sm"
              >
                Clear History
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
